/* Generated by Pyrex 0.9.3 on Tue Apr 26 20:24:44 2005 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "mfcpragma.h"
#include "malloc.h"
#include "windows.h"
#include "COMMCTRL.H"
#include "pymwin32funcs.h"
#include "pymwnd.h"
#include "python.h"
#include "editorbuffer.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

/* Declarations from _pymfc_editor */

staticforward PyTypeObject __pyx_type_13_pymfc_editor_Buffer;

struct __pyx_obj_13_pymfc_editor_Buffer {
  PyObject_HEAD
  struct __pyx_vtabstruct_13_pymfc_editor_Buffer *__pyx_vtab;
  long p_buf;
};

struct __pyx_vtabstruct_13_pymfc_editor_Buffer {
  PyObject *((*_get)(struct __pyx_obj_13_pymfc_editor_Buffer *,long ,long ));
};
static struct __pyx_vtabstruct_13_pymfc_editor_Buffer *__pyx_vtabptr_13_pymfc_editor_Buffer;

static PyTypeObject *__pyx_ptype_13_pymfc_editor_Buffer = 0;
static PyObject *__pyx_k1;
static PyObject *__pyx_k2;
static PyObject *__pyx_k3;
static PyObject *__pyx_k4;
static PyObject *__pyx_k5;
static PyObject *__pyx_k6;

/* Implementation of _pymfc_editor */

static int __pyx_f_13_pymfc_editor_6Buffer___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13_pymfc_editor_6Buffer___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  long __pyx_1;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":38 */
  __pyx_1 = PymBuf_New(); if (__pyx_1 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  ((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf = __pyx_1;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfc_editor.Buffer.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static void __pyx_f_13_pymfc_editor_6Buffer___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_13_pymfc_editor_6Buffer___dealloc__(PyObject *__pyx_v_self) {
  int __pyx_1;
  long __pyx_2;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":41 */
  __pyx_1 = (((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf != 0);
  if (__pyx_1) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":42 */
    __pyx_2 = PymBuf_Free(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf); if (__pyx_2 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfc_editor.Buffer.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static int __pyx_f_13_pymfc_editor_6Buffer___len__(PyObject *__pyx_v_self); /*proto*/
static int __pyx_f_13_pymfc_editor_6Buffer___len__(PyObject *__pyx_v_self) {
  int __pyx_r;
  long __pyx_1;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":45 */
  __pyx_1 = PymBuf_GetSize(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfc_editor.Buffer.__len__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_arg_n); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_arg_n) {
  int __pyx_v_n;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_n = PyInt_AsLong(__pyx_arg_n); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":48 */
  __pyx_1 = PymBuf_GetChar(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_v_n,(__pyx_v_n + 1)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.__getitem__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer___getslice__(PyObject *__pyx_v_self, int __pyx_v_i, int __pyx_v_j); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer___getslice__(PyObject *__pyx_v_self, int __pyx_v_i, int __pyx_v_j) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":51 */
  __pyx_1 = PymBuf_GetChar(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_v_i,__pyx_v_j); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.__getslice__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_IndexError;

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_ins(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_ins(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_pos;
  PyObject *__pyx_v_s = 0;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"pos","s",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "lO", __pyx_argnames, &__pyx_v_pos, &__pyx_v_s)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_s);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":54 */
  __pyx_1 = PymBuf_GetSize(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_2 = (__pyx_v_pos > __pyx_1);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":55 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":56 */
  __pyx_1 = PymBuf_Insert(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_v_pos,__pyx_v_s); if (__pyx_1 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.ins");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_s);
  return __pyx_r;
}

static PyObject *__pyx_n_ValueError;

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_delete(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_delete(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_pos;
  long __pyx_v_posto;
  long __pyx_v_size;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"pos","posto",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "ll", __pyx_argnames, &__pyx_v_pos, &__pyx_v_posto)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":60 */
  __pyx_1 = PymBuf_GetSize(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  __pyx_v_size = __pyx_1;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":61 */
  __pyx_2 = (__pyx_v_pos > __pyx_v_size);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":62 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":63 */
  __pyx_2 = (__pyx_v_posto > __pyx_v_size);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":64 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":65 */
  __pyx_2 = (__pyx_v_posto < __pyx_v_pos);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":66 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_ValueError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":67 */
  __pyx_1 = PymBuf_Dele(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_v_pos,__pyx_v_posto); if (__pyx_1 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.delete");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer__get(struct __pyx_obj_13_pymfc_editor_Buffer *__pyx_v_self,long __pyx_v_pos,long __pyx_v_posto) {
  long __pyx_v_size;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":71 */
  __pyx_1 = PymBuf_GetSize(__pyx_v_self->p_buf); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  __pyx_v_size = __pyx_1;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":72 */
  __pyx_2 = (__pyx_v_pos > __pyx_v_size);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":73 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":74 */
  __pyx_2 = (__pyx_v_posto > __pyx_v_size);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":75 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":76 */
  __pyx_2 = (__pyx_v_posto < __pyx_v_pos);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":77 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_ValueError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":78 */
  __pyx_3 = PymBuf_GetChar(__pyx_v_self->p_buf,__pyx_v_pos,__pyx_v_posto); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pymfc_editor.Buffer._get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_pos;
  long __pyx_v_posto;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"pos","posto",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "ll", __pyx_argnames, &__pyx_v_pos, &__pyx_v_posto)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":81 */
  __pyx_1 = ((struct __pyx_vtabstruct_13_pymfc_editor_Buffer *)((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->__pyx_vtab)->_get(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self),__pyx_v_pos,__pyx_v_posto); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getStyle(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getStyle(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_pos;
  long __pyx_v_posto;
  long __pyx_v_size;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"pos","posto",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "ll", __pyx_argnames, &__pyx_v_pos, &__pyx_v_posto)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":85 */
  __pyx_1 = PymBuf_GetSize(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  __pyx_v_size = __pyx_1;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":86 */
  __pyx_2 = (__pyx_v_pos > __pyx_v_size);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":87 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":88 */
  __pyx_2 = (__pyx_v_posto > __pyx_v_size);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":89 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":90 */
  __pyx_2 = (__pyx_v_posto < __pyx_v_pos);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":91 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_ValueError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":92 */
  __pyx_3 = PymBuf_GetStyle(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_v_pos,__pyx_v_posto); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.getStyle");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_setStyle(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_setStyle(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_pos;
  long __pyx_v_posto;
  PyObject *__pyx_v_idx = 0;
  long __pyx_v_size;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  UINT __pyx_6;
  static char *__pyx_argnames[] = {"pos","posto","idx",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "llO", __pyx_argnames, &__pyx_v_pos, &__pyx_v_posto, &__pyx_v_idx)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_idx);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":96 */
  __pyx_1 = PymBuf_GetSize(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  __pyx_v_size = __pyx_1;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":97 */
  __pyx_2 = (__pyx_v_pos > __pyx_v_size);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":98 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":99 */
  __pyx_2 = (__pyx_v_posto > __pyx_v_size);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":100 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":101 */
  __pyx_2 = (__pyx_v_posto < __pyx_v_pos);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":102 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_ValueError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":105 */
  __pyx_6 = PyInt_AsLong(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  __pyx_1 = PymBuf_SetStyle(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_v_pos,__pyx_v_posto,__pyx_6); if (__pyx_1 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.setStyle");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_idx);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_setStyles(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_setStyles(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_styles = 0;
  long __pyx_v_pos;
  long __pyx_v_posto;
  UINT __pyx_v_idx;
  long __pyx_v_size;
  PyObject *__pyx_r;
  long __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  UINT __pyx_5;
  long __pyx_6;
  int __pyx_7;
  PyObject *__pyx_8 = 0;
  static char *__pyx_argnames[] = {"styles",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_styles)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_styles);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":111 */
  __pyx_1 = PymBuf_GetSize(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  __pyx_v_size = __pyx_1;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":112 */
  __pyx_2 = PyObject_GetIter(__pyx_v_styles); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
  for (;;) {
    __pyx_L2:;
    __pyx_3 = PyIter_Next(__pyx_2);
    if (!__pyx_3) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
      break;
    }
    __pyx_4 = __Pyx_UnpackItem(__pyx_3, 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    __pyx_5 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_idx = __pyx_5;
    __pyx_4 = __Pyx_UnpackItem(__pyx_3, 1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_pos = __pyx_1;
    __pyx_4 = __Pyx_UnpackItem(__pyx_3, 2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    __pyx_6 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_posto = __pyx_6;
    if (__Pyx_EndUnpack(__pyx_3, 3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":113 */
    __pyx_7 = (__pyx_v_pos > __pyx_v_size);
    if (__pyx_7) {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":114 */
      __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
      __pyx_3 = PyTuple_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
      __pyx_8 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __Pyx_Raise(__pyx_8, 0, 0);
      Py_DECREF(__pyx_8); __pyx_8 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":115 */
    __pyx_7 = (__pyx_v_posto > __pyx_v_size);
    if (__pyx_7) {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":116 */
      __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      __pyx_3 = PyTuple_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      __pyx_8 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __Pyx_Raise(__pyx_8, 0, 0);
      Py_DECREF(__pyx_8); __pyx_8 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":117 */
    __pyx_7 = (__pyx_v_posto < __pyx_v_pos);
    if (__pyx_7) {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":118 */
      __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_ValueError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      __pyx_3 = PyTuple_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      __pyx_8 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __Pyx_Raise(__pyx_8, 0, 0);
      Py_DECREF(__pyx_8); __pyx_8 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      goto __pyx_L6;
    }
    __pyx_L6:;

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":119 */
    __pyx_1 = PymBuf_SetStyle(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_v_pos,__pyx_v_posto,__pyx_v_idx); if (__pyx_1 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  }
  __pyx_L3:;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_8);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.setStyles");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_styles);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getLineNo(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getLineNo(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_pos;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"pos",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "l", __pyx_argnames, &__pyx_v_pos)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":122 */
  __pyx_1 = PymBuf_GetSize(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  __pyx_2 = (__pyx_v_pos > __pyx_1);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":123 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":124 */
  __pyx_1 = PymBuf_GetLineNo(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_v_pos); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.getLineNo");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getLineNoPos(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getLineNoPos(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_lineno;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"lineno",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "l", __pyx_argnames, &__pyx_v_lineno)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":127 */
  __pyx_1 = PyInt_FromLong(PymBuf_GetLineNoPos(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_v_lineno)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.getLineNoPos");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getTOL(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getTOL(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_pos;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"pos",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "l", __pyx_argnames, &__pyx_v_pos)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":130 */
  __pyx_1 = PymBuf_GetSize(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  __pyx_2 = (__pyx_v_pos > __pyx_1);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":131 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":132 */
  __pyx_1 = PymBuf_GetTOL(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_v_pos); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 132; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 132; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.getTOL");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getEOL(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getEOL(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_pos;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"pos",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "l", __pyx_argnames, &__pyx_v_pos)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":135 */
  __pyx_1 = PymBuf_GetSize(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  __pyx_2 = (__pyx_v_pos > __pyx_1);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":136 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":137 */
  __pyx_1 = PymBuf_GetEOL(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_v_pos); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.getEOL");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getLineFeed(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getLineFeed(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_pos;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"pos",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "l", __pyx_argnames, &__pyx_v_pos)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":140 */
  __pyx_1 = PymBuf_GetSize(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  __pyx_2 = (__pyx_v_pos > __pyx_1);
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":141 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":142 */
  __pyx_1 = PymBuf_GetLineFeed(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_v_pos); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.getLineFeed");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getSize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_getSize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  long __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":145 */
  __pyx_1 = PymBuf_GetSize(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.getSize");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_ord;

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_find(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_find(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_pos = 0;
  PyObject *__pyx_v_posto = 0;
  PyObject *__pyx_v_c = 0;
  PyObject *__pyx_v_case = 0;
  PyObject *__pyx_v_forward = 0;
  long __pyx_v_w_c;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  long __pyx_4;
  int __pyx_5;
  long __pyx_6;
  static char *__pyx_argnames[] = {"pos","posto","c","case","forward",0};
  __pyx_v_case = __pyx_k1;
  __pyx_v_forward = __pyx_k2;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO|OO", __pyx_argnames, &__pyx_v_pos, &__pyx_v_posto, &__pyx_v_c, &__pyx_v_case, &__pyx_v_forward)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_pos);
  Py_INCREF(__pyx_v_posto);
  Py_INCREF(__pyx_v_c);
  Py_INCREF(__pyx_v_case);
  Py_INCREF(__pyx_v_forward);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":149 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_ord); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
  Py_INCREF(__pyx_v_c);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_c);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_w_c = __pyx_4;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":151 */
  __pyx_5 = PyObject_IsTrue(__pyx_v_case); if (__pyx_5 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  if (__pyx_5) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":152 */
    __pyx_5 = PyObject_IsTrue(__pyx_v_forward); if (__pyx_5 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    if (__pyx_5) {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":153 */
      __pyx_4 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
      __pyx_6 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
      __pyx_1 = PyInt_FromLong(PymBuf_Find(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_4,__pyx_6,((unsigned short )__pyx_v_w_c))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
      __pyx_r = __pyx_1;
      __pyx_1 = 0;
      goto __pyx_L0;
      goto __pyx_L3;
    }
    /*else*/ {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":155 */
      __pyx_4 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
      __pyx_6 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
      __pyx_2 = PyInt_FromLong(PymBuf_Find_back(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_4,__pyx_6,((unsigned short )__pyx_v_w_c))); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
      __pyx_r = __pyx_2;
      __pyx_2 = 0;
      goto __pyx_L0;
    }
    __pyx_L3:;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":157 */
    __pyx_5 = PyObject_IsTrue(__pyx_v_forward); if (__pyx_5 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 157; goto __pyx_L1;}
    if (__pyx_5) {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":158 */
      __pyx_4 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
      __pyx_6 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(PymBuf_Find_i(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_4,__pyx_6,((unsigned short )__pyx_v_w_c))); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
      __pyx_r = __pyx_3;
      __pyx_3 = 0;
      goto __pyx_L0;
      goto __pyx_L4;
    }
    /*else*/ {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":160 */
      __pyx_4 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
      __pyx_6 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
      __pyx_1 = PyInt_FromLong(PymBuf_Find_i_back(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_4,__pyx_6,((unsigned short )__pyx_v_w_c))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
      __pyx_r = __pyx_1;
      __pyx_1 = 0;
      goto __pyx_L0;
    }
    __pyx_L4:;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.find");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_pos);
  Py_DECREF(__pyx_v_posto);
  Py_DECREF(__pyx_v_c);
  Py_DECREF(__pyx_v_case);
  Py_DECREF(__pyx_v_forward);
  return __pyx_r;
}

static PyObject *__pyx_n_len;

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_findOneOf(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_findOneOf(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_pos = 0;
  PyObject *__pyx_v_posto = 0;
  PyObject *__pyx_v_c = 0;
  PyObject *__pyx_v_forward = 0;
  unsigned short (*__pyx_v_p_c);
  long __pyx_v_l;
  PyObject *__pyx_r;
  unsigned short (*__pyx_1);
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  long __pyx_5;
  int __pyx_6;
  long __pyx_7;
  static char *__pyx_argnames[] = {"pos","posto","c","forward",0};
  __pyx_v_forward = __pyx_k3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO|O", __pyx_argnames, &__pyx_v_pos, &__pyx_v_posto, &__pyx_v_c, &__pyx_v_forward)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_pos);
  Py_INCREF(__pyx_v_posto);
  Py_INCREF(__pyx_v_c);
  Py_INCREF(__pyx_v_forward);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":165 */
  __pyx_1 = PyUnicode_AsUnicode(__pyx_v_c); if (__pyx_1 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 165; goto __pyx_L1;}
  __pyx_v_p_c = __pyx_1;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":166 */
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  Py_INCREF(__pyx_v_c);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_c);
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_l = __pyx_5;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":168 */
  __pyx_6 = PyObject_IsTrue(__pyx_v_forward); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 168; goto __pyx_L1;}
  if (__pyx_6) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":169 */
    __pyx_5 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
    __pyx_7 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
    __pyx_2 = PymBuf_FindOneOf(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_5,__pyx_7,__pyx_v_p_c,(__pyx_v_p_c + __pyx_v_l)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":171 */
    __pyx_5 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
    __pyx_7 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
    __pyx_3 = PymBuf_FindOneOf_back(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_5,__pyx_7,__pyx_v_p_c,(__pyx_v_p_c + __pyx_v_l)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.findOneOf");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_pos);
  Py_DECREF(__pyx_v_posto);
  Py_DECREF(__pyx_v_c);
  Py_DECREF(__pyx_v_forward);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_findString(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_findString(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_pos = 0;
  PyObject *__pyx_v_posto = 0;
  PyObject *__pyx_v_s = 0;
  PyObject *__pyx_v_case = 0;
  PyObject *__pyx_v_forward = 0;
  unsigned short (*__pyx_v_p_s);
  long __pyx_v_l;
  PyObject *__pyx_r;
  unsigned short (*__pyx_1);
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  long __pyx_5;
  int __pyx_6;
  long __pyx_7;
  static char *__pyx_argnames[] = {"pos","posto","s","case","forward",0};
  __pyx_v_case = __pyx_k4;
  __pyx_v_forward = __pyx_k5;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO|OO", __pyx_argnames, &__pyx_v_pos, &__pyx_v_posto, &__pyx_v_s, &__pyx_v_case, &__pyx_v_forward)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_pos);
  Py_INCREF(__pyx_v_posto);
  Py_INCREF(__pyx_v_s);
  Py_INCREF(__pyx_v_case);
  Py_INCREF(__pyx_v_forward);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":176 */
  __pyx_1 = PyUnicode_AsUnicode(__pyx_v_s); if (__pyx_1 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  __pyx_v_p_s = __pyx_1;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":177 */
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
  Py_INCREF(__pyx_v_s);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_s);
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_l = __pyx_5;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":179 */
  __pyx_6 = PyObject_IsTrue(__pyx_v_case); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
  if (__pyx_6) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":180 */
    __pyx_6 = PyObject_IsTrue(__pyx_v_forward); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 180; goto __pyx_L1;}
    if (__pyx_6) {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":181 */
      __pyx_5 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}
      __pyx_7 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}
      __pyx_2 = PyInt_FromLong(PymBuf_FindString(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_5,__pyx_7,__pyx_v_p_s,(__pyx_v_p_s + __pyx_v_l))); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}
      __pyx_r = __pyx_2;
      __pyx_2 = 0;
      goto __pyx_L0;
      goto __pyx_L3;
    }
    /*else*/ {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":183 */
      __pyx_5 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
      __pyx_7 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(PymBuf_FindString_back(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_5,__pyx_7,__pyx_v_p_s,(__pyx_v_p_s + __pyx_v_l))); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
      __pyx_r = __pyx_3;
      __pyx_3 = 0;
      goto __pyx_L0;
    }
    __pyx_L3:;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":185 */
    __pyx_6 = PyObject_IsTrue(__pyx_v_forward); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 185; goto __pyx_L1;}
    if (__pyx_6) {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":186 */
      __pyx_5 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 186; goto __pyx_L1;}
      __pyx_7 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 186; goto __pyx_L1;}
      __pyx_4 = PyInt_FromLong(PymBuf_FindString_i(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_5,__pyx_7,__pyx_v_p_s,(__pyx_v_p_s + __pyx_v_l))); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 186; goto __pyx_L1;}
      __pyx_r = __pyx_4;
      __pyx_4 = 0;
      goto __pyx_L0;
      goto __pyx_L4;
    }
    /*else*/ {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":188 */
      __pyx_5 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; goto __pyx_L1;}
      __pyx_7 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; goto __pyx_L1;}
      __pyx_2 = PyInt_FromLong(PymBuf_FindString_i_back(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_5,__pyx_7,__pyx_v_p_s,(__pyx_v_p_s + __pyx_v_l))); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; goto __pyx_L1;}
      __pyx_r = __pyx_2;
      __pyx_2 = 0;
      goto __pyx_L0;
    }
    __pyx_L4:;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.findString");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_pos);
  Py_DECREF(__pyx_v_posto);
  Py_DECREF(__pyx_v_s);
  Py_DECREF(__pyx_v_case);
  Py_DECREF(__pyx_v_forward);
  return __pyx_r;
}

static PyObject *__pyx_n_isinstance;
static PyObject *__pyx_n_int;

static PyObject *__pyx_f_13_pymfc_editor_6Buffer_findStyle(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pymfc_editor_6Buffer_findStyle(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_pos = 0;
  PyObject *__pyx_v_posto = 0;
  PyObject *__pyx_v_style = 0;
  PyObject *__pyx_v_forward = 0;
  long __pyx_v_w_c;
  long __pyx_v_stylelen;
  long (*__pyx_v_buf);
  long __pyx_v_n;
  PyObject *__pyx_v_s;
  PyObject *__pyx_v_ret;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  long __pyx_5;
  long __pyx_6;
  UINT __pyx_7;
  static char *__pyx_argnames[] = {"pos","posto","style","forward",0};
  __pyx_v_forward = __pyx_k6;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO|O", __pyx_argnames, &__pyx_v_pos, &__pyx_v_posto, &__pyx_v_style, &__pyx_v_forward)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_pos);
  Py_INCREF(__pyx_v_posto);
  Py_INCREF(__pyx_v_style);
  Py_INCREF(__pyx_v_forward);
  __pyx_v_s = Py_None; Py_INCREF(__pyx_v_s);
  __pyx_v_ret = Py_None; Py_INCREF(__pyx_v_ret);

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":196 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_isinstance); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_int); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  Py_INCREF(__pyx_v_style);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_style);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_2); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__pyx_4) {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":197 */
    __pyx_4 = PyObject_IsTrue(__pyx_v_forward); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 197; goto __pyx_L1;}
    if (__pyx_4) {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":198 */
      __pyx_5 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
      __pyx_6 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
      __pyx_7 = PyInt_AsLong(__pyx_v_style); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
      __pyx_1 = PyInt_FromLong(PymBuf_FindStyle(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_5,__pyx_6,__pyx_7)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
      __pyx_r = __pyx_1;
      __pyx_1 = 0;
      goto __pyx_L0;
      goto __pyx_L3;
    }
    /*else*/ {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":200 */
      __pyx_5 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
      __pyx_6 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
      __pyx_7 = PyInt_AsLong(__pyx_v_style); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(PymBuf_FindStyle_back(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_5,__pyx_6,__pyx_7)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
      __pyx_r = __pyx_3;
      __pyx_3 = 0;
      goto __pyx_L0;
    }
    __pyx_L3:;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":202 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
    Py_INCREF(__pyx_v_style);
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_style);
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_5 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_v_stylelen = __pyx_5;

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":203 */
    __pyx_v_buf = ((long (*))malloc((__pyx_v_stylelen * (sizeof(long )))));

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":204 */
    __pyx_v_n = 0;

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":205 */
    __pyx_2 = PyObject_GetIter(__pyx_v_style); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 205; goto __pyx_L1;}
    for (;;) {
      __pyx_L4:;
      __pyx_1 = PyIter_Next(__pyx_2);
      if (!__pyx_1) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 205; goto __pyx_L1;}
        break;
      }
      Py_DECREF(__pyx_v_s);
      __pyx_v_s = __pyx_1;
      __pyx_1 = 0;

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":206 */
      __pyx_6 = PyInt_AsLong(__pyx_v_s); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
      __pyx_v_w_c = __pyx_6;

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":207 */
      (__pyx_v_buf[__pyx_v_n]) = __pyx_v_w_c;

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":208 */
      __pyx_v_n = (__pyx_v_n + 1);
    }
    __pyx_L5:;
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":209 */
    /*try:*/ {

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":210 */
      __pyx_4 = PyObject_IsTrue(__pyx_v_forward); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 210; goto __pyx_L6;}
      if (__pyx_4) {

        /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":211 */
        __pyx_5 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L6;}
        __pyx_6 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L6;}
        __pyx_3 = PymBuf_FindStyleOneOf(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_5,__pyx_6,__pyx_v_buf,(__pyx_v_buf + __pyx_v_stylelen)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L6;}
        Py_DECREF(__pyx_v_ret);
        __pyx_v_ret = __pyx_3;
        __pyx_3 = 0;
        goto __pyx_L8;
      }
      /*else*/ {

        /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":213 */
        __pyx_5 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; goto __pyx_L6;}
        __pyx_6 = PyInt_AsLong(__pyx_v_posto); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; goto __pyx_L6;}
        __pyx_1 = PymBuf_FindStyleOneOf_back(((struct __pyx_obj_13_pymfc_editor_Buffer *)__pyx_v_self)->p_buf,__pyx_5,__pyx_6,__pyx_v_buf,(__pyx_v_buf + __pyx_v_stylelen)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; goto __pyx_L6;}
        Py_DECREF(__pyx_v_ret);
        __pyx_v_ret = __pyx_1;
        __pyx_1 = 0;
      }
      __pyx_L8:;
    }
    goto __pyx_L7;
    __pyx_L6:;
    Py_XDECREF(__pyx_2); __pyx_2 = 0;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;
    Py_XDECREF(__pyx_1); __pyx_1 = 0;

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":214 */
    /*except:*/ {
      __Pyx_AddTraceback("_pymfc_editor.findStyle");
      __pyx_2 = __Pyx_GetExcValue(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 214; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":215 */
      free(__pyx_v_buf);

      /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":216 */
      __Pyx_ReRaise();
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
      goto __pyx_L7;
    }
    __pyx_L7:;

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":218 */
    free(__pyx_v_buf);

    /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":219 */
    Py_INCREF(__pyx_v_ret);
    __pyx_r = __pyx_v_ret;
    goto __pyx_L0;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pymfc_editor.Buffer.findStyle");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_s);
  Py_DECREF(__pyx_v_ret);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_pos);
  Py_DECREF(__pyx_v_posto);
  Py_DECREF(__pyx_v_style);
  Py_DECREF(__pyx_v_forward);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_IndexError, "IndexError"},
  {&__pyx_n_ValueError, "ValueError"},
  {&__pyx_n_int, "int"},
  {&__pyx_n_isinstance, "isinstance"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_ord, "ord"},
  {0, 0}
};
static struct __pyx_vtabstruct_13_pymfc_editor_Buffer __pyx_vtable_13_pymfc_editor_Buffer;

static PyObject *__pyx_tp_new_13_pymfc_editor_Buffer(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_13_pymfc_editor_Buffer *p = (struct __pyx_obj_13_pymfc_editor_Buffer *)o;
  (struct __pyx_vtabstruct_13_pymfc_editor_Buffer *)p->__pyx_vtab = __pyx_vtabptr_13_pymfc_editor_Buffer;
  return o;
}

static void __pyx_tp_dealloc_13_pymfc_editor_Buffer(PyObject *o) {
  struct __pyx_obj_13_pymfc_editor_Buffer *p = (struct __pyx_obj_13_pymfc_editor_Buffer *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_13_pymfc_editor_6Buffer___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_13_pymfc_editor_Buffer(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_13_pymfc_editor_Buffer *p = (struct __pyx_obj_13_pymfc_editor_Buffer *)o;
  return 0;
}

static int __pyx_tp_clear_13_pymfc_editor_Buffer(PyObject *o) {
  struct __pyx_obj_13_pymfc_editor_Buffer *p = (struct __pyx_obj_13_pymfc_editor_Buffer *)o;
  return 0;
}
static PyObject *__pyx_sq_item_13_pymfc_editor_Buffer(PyObject *o, int i) {
  PyObject *r;
  PyObject *x = PyInt_FromLong(i); if(!x) return 0;
  r = o->ob_type->tp_as_mapping->mp_subscript(o, x);
  Py_DECREF(x);
  return r;
}

static struct PyMethodDef __pyx_methods_13_pymfc_editor_Buffer[] = {
  {"ins", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_ins, METH_VARARGS|METH_KEYWORDS, 0},
  {"delete", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_delete, METH_VARARGS|METH_KEYWORDS, 0},
  {"get", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_get, METH_VARARGS|METH_KEYWORDS, 0},
  {"getStyle", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_getStyle, METH_VARARGS|METH_KEYWORDS, 0},
  {"setStyle", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_setStyle, METH_VARARGS|METH_KEYWORDS, 0},
  {"setStyles", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_setStyles, METH_VARARGS|METH_KEYWORDS, 0},
  {"getLineNo", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_getLineNo, METH_VARARGS|METH_KEYWORDS, 0},
  {"getLineNoPos", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_getLineNoPos, METH_VARARGS|METH_KEYWORDS, 0},
  {"getTOL", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_getTOL, METH_VARARGS|METH_KEYWORDS, 0},
  {"getEOL", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_getEOL, METH_VARARGS|METH_KEYWORDS, 0},
  {"getLineFeed", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_getLineFeed, METH_VARARGS|METH_KEYWORDS, 0},
  {"getSize", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_getSize, METH_VARARGS|METH_KEYWORDS, 0},
  {"find", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_find, METH_VARARGS|METH_KEYWORDS, 0},
  {"findOneOf", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_findOneOf, METH_VARARGS|METH_KEYWORDS, 0},
  {"findString", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_findString, METH_VARARGS|METH_KEYWORDS, 0},
  {"findStyle", (PyCFunction)__pyx_f_13_pymfc_editor_6Buffer_findStyle, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_13_pymfc_editor_Buffer[] = {
  {"p_buf", T_LONG, offsetof(struct __pyx_obj_13_pymfc_editor_Buffer, p_buf), READONLY, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Buffer = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Buffer = {
  __pyx_f_13_pymfc_editor_6Buffer___len__, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  __pyx_sq_item_13_pymfc_editor_Buffer, /*sq_item*/
  __pyx_f_13_pymfc_editor_6Buffer___getslice__, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Buffer = {
  __pyx_f_13_pymfc_editor_6Buffer___len__, /*mp_length*/
  __pyx_f_13_pymfc_editor_6Buffer___getitem__, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Buffer = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_13_pymfc_editor_Buffer = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "_pymfc_editor.Buffer", /*tp_name*/
  sizeof(struct __pyx_obj_13_pymfc_editor_Buffer), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_13_pymfc_editor_Buffer, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Buffer, /*tp_as_number*/
  &__pyx_tp_as_sequence_Buffer, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Buffer, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Buffer, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_13_pymfc_editor_Buffer, /*tp_traverse*/
  __pyx_tp_clear_13_pymfc_editor_Buffer, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_13_pymfc_editor_Buffer, /*tp_methods*/
  __pyx_members_13_pymfc_editor_Buffer, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_13_pymfc_editor_6Buffer___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_13_pymfc_editor_Buffer, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

DL_EXPORT(void) init_pymfc_editor(void); /*proto*/
DL_EXPORT(void) init_pymfc_editor(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  __pyx_m = Py_InitModule4("_pymfc_editor", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 4; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 4; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 4; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 4; goto __pyx_L1;};
  __pyx_vtabptr_13_pymfc_editor_Buffer = &__pyx_vtable_13_pymfc_editor_Buffer;
  __pyx_vtable_13_pymfc_editor_Buffer._get = (void *)__pyx_f_13_pymfc_editor_6Buffer__get;
  if (PyType_Ready(&__pyx_type_13_pymfc_editor_Buffer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_13_pymfc_editor_Buffer.tp_dict, __pyx_vtabptr_13_pymfc_editor_Buffer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Buffer", (PyObject *)&__pyx_type_13_pymfc_editor_Buffer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
  __pyx_ptype_13_pymfc_editor_Buffer = &__pyx_type_13_pymfc_editor_Buffer;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":147 */
  __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  __pyx_k1 = __pyx_1;
  __pyx_1 = 0;
  __pyx_2 = PyInt_FromLong(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  __pyx_k2 = __pyx_2;
  __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":162 */
  __pyx_3 = PyInt_FromLong(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
  __pyx_k3 = __pyx_3;
  __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":173 */
  __pyx_4 = PyInt_FromLong(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  __pyx_k4 = __pyx_4;
  __pyx_4 = 0;
  __pyx_5 = PyInt_FromLong(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  __pyx_k5 = __pyx_5;
  __pyx_5 = 0;

  /* "c:\src\infopile\src\pymfclib\pymfc_editorbuf.pxi":190 */
  __pyx_6 = PyInt_FromLong(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
  __pyx_k6 = __pyx_6;
  __pyx_6 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("_pymfc_editor");
}

static char *__pyx_filenames[] = {
  "pymfc_editorbuf.pxi",
  "_pymfc_editor.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *seq, int i) {
  PyObject *item;
  if (!(item = PySequence_GetItem(seq, i))) {
    if (PyErr_ExceptionMatches(PyExc_IndexError))
    	__Pyx_UnpackError();
  }
  return item;
}

static int __Pyx_EndUnpack(PyObject *seq, int i) {
  PyObject *item;
  if (item = PySequence_GetItem(seq, i)) {
    Py_DECREF(item);
    __Pyx_UnpackError();
    return -1;
  }
  PyErr_Clear();
    return 0;
}

static PyObject *__Pyx_GetExcValue(void) {
    PyObject *type = 0, *value = 0, *tb = 0;
    PyObject *result = 0;
    PyThreadState *tstate = PyThreadState_Get();
    PyErr_Fetch(&type, &value, &tb);
    PyErr_NormalizeException(&type, &value, &tb);
    if (PyErr_Occurred())
        goto bad;
    if (!value) {
        value = Py_None;
        Py_INCREF(value);
    }
    Py_XDECREF(tstate->exc_type);
    Py_XDECREF(tstate->exc_value);
    Py_XDECREF(tstate->exc_traceback);
    tstate->exc_type = type;
    tstate->exc_value = value;
    tstate->exc_traceback = tb;
    result = value;
    Py_XINCREF(result);
    type = 0;
    value = 0;
    tb = 0;
bad:
    Py_XDECREF(type);
    Py_XDECREF(value);
    Py_XDECREF(tb);
    return result;
}

static void __Pyx_ReRaise(void) {
    PyThreadState *tstate = PyThreadState_Get();
    PyObject *type = tstate->exc_type;
    PyObject *value = tstate->exc_value;
    PyObject *tb = tstate->exc_traceback;
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    PyErr_Restore(type, value, tb);
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
