/* Generated by Pyrex 0.9.9 on Wed Nov 17 18:22:22 2010 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "mfcpragma.h"
#include "malloc.h"
#include "string.h"
#include "tchar.h"
#include "pymmacros.h"
#include "windows.h"
#include "COMMCTRL.H"
#include "pymwin32funcs.h"
#include "pymwnd.h"
#include "htmlhelp.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from _pymfclib_htmlhelp */


/* Declarations from implementation of _pymfclib_htmlhelp */

typedef unsigned short __pyx_t_18_pymfclib_htmlhelp_PYMFC_WCHAR;


static char __pyx_k1[] = "getHwnd";

static PyObject *__pyx_n_getHwnd;


static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_getHwnd, 1, __pyx_k1, sizeof(__pyx_k1)},
  {0, 0, 0, 0}
};



/* Implementation of _pymfclib_htmlhelp */

static PyObject *__pyx_f_18_pymfclib_htmlhelp_htmlhelp_init(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_18_pymfclib_htmlhelp_htmlhelp_init(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  HWND __pyx_v_ret;
  DWORD __pyx_v_dwCookie;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "c:\src\ip\pymfc\pymfclib\_pymfclib_htmlhelp.pyx":27 */
  __pyx_v_ret = NULL;

  /* "c:\src\ip\pymfc\pymfclib\_pymfclib_htmlhelp.pyx":28 */
  __pyx_v_dwCookie = 0;

  /* "c:\src\ip\pymfc\pymfclib\_pymfclib_htmlhelp.pyx":30 */
  /*with nogil:*/ {
    PyThreadState *_save;
    Py_UNBLOCK_THREADS
    /*try:*/ {
      __pyx_v_ret = HtmlHelpW(NULL,NULL,HH_INITIALIZE,((DWORD)(&__pyx_v_dwCookie)));
    }
    /*finally:*/ {
      Py_BLOCK_THREADS
    }
  }

  /* "c:\src\ip\pymfc\pymfclib\_pymfclib_htmlhelp.pyx":32 */
  __pyx_1 = PyLong_FromUnsignedLong(__pyx_v_dwCookie); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_pymfclib_htmlhelp.htmlhelp_init");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_18_pymfclib_htmlhelp_htmlhelp_uninit(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_18_pymfclib_htmlhelp_htmlhelp_uninit(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_cookie = 0;
  DWORD __pyx_v_dwCookie;
  PyObject *__pyx_r;
  DWORD __pyx_1;
  static char *__pyx_argnames[] = {"cookie",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_cookie)) return 0;
  Py_INCREF(__pyx_v_cookie);

  /* "c:\src\ip\pymfc\pymfclib\_pymfclib_htmlhelp.pyx":37 */
  __pyx_1 = PyInt_AsUnsignedLongMask(__pyx_v_cookie); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  __pyx_v_dwCookie = __pyx_1;

  /* "c:\src\ip\pymfc\pymfclib\_pymfclib_htmlhelp.pyx":39 */
  /*with nogil:*/ {
    PyThreadState *_save;
    Py_UNBLOCK_THREADS
    /*try:*/ {
      HtmlHelpW(NULL,NULL,HH_UNINITIALIZE,__pyx_v_dwCookie);
    }
    /*finally:*/ {
      Py_BLOCK_THREADS
    }
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfclib_htmlhelp.htmlhelp_uninit");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_cookie);
  return __pyx_r;
}

static PyObject *__pyx_f_18_pymfclib_htmlhelp_htmlhelp_display_topic(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_18_pymfclib_htmlhelp_htmlhelp_display_topic(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_wnd = 0;
  PyObject *__pyx_v_url = 0;
  __pyx_t_18_pymfclib_htmlhelp_PYMFC_WCHAR *__pyx_v_u_url;
  HWND __pyx_v_hWnd;
  PyObject *__pyx_r;
  int __pyx_1;
  HANDLE __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_t_18_pymfclib_htmlhelp_PYMFC_WCHAR *__pyx_5;
  static char *__pyx_argnames[] = {"wnd","url",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_wnd, &__pyx_v_url)) return 0;
  Py_INCREF(__pyx_v_wnd);
  Py_INCREF(__pyx_v_url);

  /* "c:\src\ip\pymfc\pymfclib\_pymfclib_htmlhelp.pyx":47 */
  __pyx_1 = PyMFCHandle_IsHandle(__pyx_v_wnd); if (__pyx_1 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  if (__pyx_1) {
    __pyx_2 = PyMFCHandle_AsHandle(__pyx_v_wnd); if (__pyx_2 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
    __pyx_v_hWnd = __pyx_2;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_3 = PyObject_GetAttr(__pyx_v_wnd, __pyx_n_getHwnd); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
    __pyx_4 = PyObject_CallObject(__pyx_3, 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyMFCHandle_AsHandle(__pyx_4); if (__pyx_2 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_hWnd = __pyx_2;
  }
  __pyx_L2:;

  /* "c:\src\ip\pymfc\pymfclib\_pymfclib_htmlhelp.pyx":52 */
  __pyx_5 = PyUnicode_AsUnicode(__pyx_v_url); if (__pyx_5 == NULL) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
  __pyx_v_u_url = __pyx_5;

  /* "c:\src\ip\pymfc\pymfclib\_pymfclib_htmlhelp.pyx":54 */
  /*with nogil:*/ {
    PyThreadState *_save;
    Py_UNBLOCK_THREADS
    /*try:*/ {
      HtmlHelpW(__pyx_v_hWnd,__pyx_v_u_url,HH_DISPLAY_TOPIC,0);
    }
    /*finally:*/ {
      Py_BLOCK_THREADS
    }
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_pymfclib_htmlhelp.htmlhelp_display_topic");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_wnd);
  Py_DECREF(__pyx_v_url);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"htmlhelp_init", (PyCFunction)__pyx_f_18_pymfclib_htmlhelp_htmlhelp_init, METH_VARARGS|METH_KEYWORDS, 0},
  {"htmlhelp_uninit", (PyCFunction)__pyx_f_18_pymfclib_htmlhelp_htmlhelp_uninit, METH_VARARGS|METH_KEYWORDS, 0},
  {"htmlhelp_display_topic", (PyCFunction)__pyx_f_18_pymfclib_htmlhelp_htmlhelp_display_topic, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC init_pymfclib_htmlhelp(void); /*proto*/
PyMODINIT_FUNC init_pymfclib_htmlhelp(void) {
  #if PY_VERSION_HEX < 0x02040000 && defined(WITH_THREAD)
    PyEval_InitThreads();
  #endif
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("_pymfclib_htmlhelp", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};

  /* "c:\src\ip\pymfc\pymfclib\_pymfclib_htmlhelp.pyx":43 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfclib_htmlhelp");
}

static char *__pyx_filenames[] = {
  "_pymfclib_htmlhelp.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
