/* Generated by Pyrex 0.9.8.5 on Mon Aug 30 20:01:58 2010 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "mfcpragma.h"
#include "pymfcdefs.h"
#include "malloc.h"
#include "string.h"
#include "tchar.h"
#include "pymmacros.h"
#include "windows.h"
#include "COMMCTRL.H"
#include "pymwin32funcs.h"
#include "pymwnd.h"
#include "pymmenu.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetItemInt(PyObject *o, Py_ssize_t i); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from _pymfclib_menu */


/* Declarations from implementation of _pymfclib_menu */

typedef unsigned short __pyx_t_14_pymfclib_menu_PYMFC_WCHAR;

static PyObject *__pyx_v_14_pymfclib_menu___const_menu;

static char __pyx_k1[] = "getHwnd";
static char __pyx_k2[] = "__MENUCONSTS";
static char __pyx_k3[] = "_const_menu";
static char __pyx_k4[] = "MF_INSERT";
static char __pyx_k5[] = "MF_CHANGE";
static char __pyx_k6[] = "MF_APPEND";
static char __pyx_k7[] = "MF_DELETE";
static char __pyx_k8[] = "MF_REMOVE";
static char __pyx_k9[] = "MF_BYCOMMAND";
static char __pyx_k10[] = "MF_BYPOSITION";
static char __pyx_k11[] = "MF_SEPARATOR";
static char __pyx_k12[] = "MF_ENABLED";
static char __pyx_k13[] = "MF_GRAYED";
static char __pyx_k14[] = "MF_DISABLED";
static char __pyx_k15[] = "MF_UNCHECKED";
static char __pyx_k16[] = "MF_CHECKED";
static char __pyx_k17[] = "MF_USECHECKBITMAPS";
static char __pyx_k18[] = "MF_STRING";
static char __pyx_k19[] = "MF_BITMAP";
static char __pyx_k20[] = "MF_OWNERDRAW";
static char __pyx_k21[] = "MF_POPUP";
static char __pyx_k22[] = "MF_MENUBARBREAK";
static char __pyx_k23[] = "MF_MENUBREAK";
static char __pyx_k24[] = "MF_UNHILITE";
static char __pyx_k25[] = "MF_HILITE";
static char __pyx_k26[] = "MF_DEFAULT";
static char __pyx_k27[] = "MF_SYSMENU";
static char __pyx_k28[] = "MF_HELP";
static char __pyx_k29[] = "MF_RIGHTJUSTIFY";
static char __pyx_k30[] = "MF_MOUSESELECT";
static char __pyx_k31[] = "MF_END";
static char __pyx_k32[] = "MFT_STRING";
static char __pyx_k33[] = "MFT_BITMAP";
static char __pyx_k34[] = "MFT_MENUBARBREAK";
static char __pyx_k35[] = "MFT_MENUBREAK";
static char __pyx_k36[] = "MFT_OWNERDRAW";
static char __pyx_k37[] = "MFT_RADIOCHECK";
static char __pyx_k38[] = "MFT_SEPARATOR";
static char __pyx_k39[] = "MFT_RIGHTORDER";
static char __pyx_k40[] = "MFT_RIGHTJUSTIFY";
static char __pyx_k41[] = "MFS_GRAYED";
static char __pyx_k42[] = "MFS_DISABLED";
static char __pyx_k43[] = "MFS_CHECKED";
static char __pyx_k44[] = "MFS_HILITE";
static char __pyx_k45[] = "MFS_ENABLED";
static char __pyx_k46[] = "MFS_UNCHECKED";
static char __pyx_k47[] = "MFS_UNHILITE";
static char __pyx_k48[] = "MFS_DEFAULT";

static PyObject *__pyx_n_MFS_CHECKED;
static PyObject *__pyx_n_MFS_DEFAULT;
static PyObject *__pyx_n_MFS_DISABLED;
static PyObject *__pyx_n_MFS_ENABLED;
static PyObject *__pyx_n_MFS_GRAYED;
static PyObject *__pyx_n_MFS_HILITE;
static PyObject *__pyx_n_MFS_UNCHECKED;
static PyObject *__pyx_n_MFS_UNHILITE;
static PyObject *__pyx_n_MFT_BITMAP;
static PyObject *__pyx_n_MFT_MENUBARBREAK;
static PyObject *__pyx_n_MFT_MENUBREAK;
static PyObject *__pyx_n_MFT_OWNERDRAW;
static PyObject *__pyx_n_MFT_RADIOCHECK;
static PyObject *__pyx_n_MFT_RIGHTJUSTIFY;
static PyObject *__pyx_n_MFT_RIGHTORDER;
static PyObject *__pyx_n_MFT_SEPARATOR;
static PyObject *__pyx_n_MFT_STRING;
static PyObject *__pyx_n_MF_APPEND;
static PyObject *__pyx_n_MF_BITMAP;
static PyObject *__pyx_n_MF_BYCOMMAND;
static PyObject *__pyx_n_MF_BYPOSITION;
static PyObject *__pyx_n_MF_CHANGE;
static PyObject *__pyx_n_MF_CHECKED;
static PyObject *__pyx_n_MF_DEFAULT;
static PyObject *__pyx_n_MF_DELETE;
static PyObject *__pyx_n_MF_DISABLED;
static PyObject *__pyx_n_MF_ENABLED;
static PyObject *__pyx_n_MF_END;
static PyObject *__pyx_n_MF_GRAYED;
static PyObject *__pyx_n_MF_HELP;
static PyObject *__pyx_n_MF_HILITE;
static PyObject *__pyx_n_MF_INSERT;
static PyObject *__pyx_n_MF_MENUBARBREAK;
static PyObject *__pyx_n_MF_MENUBREAK;
static PyObject *__pyx_n_MF_MOUSESELECT;
static PyObject *__pyx_n_MF_OWNERDRAW;
static PyObject *__pyx_n_MF_POPUP;
static PyObject *__pyx_n_MF_REMOVE;
static PyObject *__pyx_n_MF_RIGHTJUSTIFY;
static PyObject *__pyx_n_MF_SEPARATOR;
static PyObject *__pyx_n_MF_STRING;
static PyObject *__pyx_n_MF_SYSMENU;
static PyObject *__pyx_n_MF_UNCHECKED;
static PyObject *__pyx_n_MF_UNHILITE;
static PyObject *__pyx_n_MF_USECHECKBITMAPS;
static PyObject *__pyx_n___MENUCONSTS;
static PyObject *__pyx_n__const_menu;
static PyObject *__pyx_n_getHwnd;


static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_MFS_CHECKED, 1, __pyx_k43, sizeof(__pyx_k43)},
  {&__pyx_n_MFS_DEFAULT, 1, __pyx_k48, sizeof(__pyx_k48)},
  {&__pyx_n_MFS_DISABLED, 1, __pyx_k42, sizeof(__pyx_k42)},
  {&__pyx_n_MFS_ENABLED, 1, __pyx_k45, sizeof(__pyx_k45)},
  {&__pyx_n_MFS_GRAYED, 1, __pyx_k41, sizeof(__pyx_k41)},
  {&__pyx_n_MFS_HILITE, 1, __pyx_k44, sizeof(__pyx_k44)},
  {&__pyx_n_MFS_UNCHECKED, 1, __pyx_k46, sizeof(__pyx_k46)},
  {&__pyx_n_MFS_UNHILITE, 1, __pyx_k47, sizeof(__pyx_k47)},
  {&__pyx_n_MFT_BITMAP, 1, __pyx_k33, sizeof(__pyx_k33)},
  {&__pyx_n_MFT_MENUBARBREAK, 1, __pyx_k34, sizeof(__pyx_k34)},
  {&__pyx_n_MFT_MENUBREAK, 1, __pyx_k35, sizeof(__pyx_k35)},
  {&__pyx_n_MFT_OWNERDRAW, 1, __pyx_k36, sizeof(__pyx_k36)},
  {&__pyx_n_MFT_RADIOCHECK, 1, __pyx_k37, sizeof(__pyx_k37)},
  {&__pyx_n_MFT_RIGHTJUSTIFY, 1, __pyx_k40, sizeof(__pyx_k40)},
  {&__pyx_n_MFT_RIGHTORDER, 1, __pyx_k39, sizeof(__pyx_k39)},
  {&__pyx_n_MFT_SEPARATOR, 1, __pyx_k38, sizeof(__pyx_k38)},
  {&__pyx_n_MFT_STRING, 1, __pyx_k32, sizeof(__pyx_k32)},
  {&__pyx_n_MF_APPEND, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n_MF_BITMAP, 1, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_n_MF_BYCOMMAND, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_n_MF_BYPOSITION, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_MF_CHANGE, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_MF_CHECKED, 1, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_n_MF_DEFAULT, 1, __pyx_k26, sizeof(__pyx_k26)},
  {&__pyx_n_MF_DELETE, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n_MF_DISABLED, 1, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_n_MF_ENABLED, 1, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_n_MF_END, 1, __pyx_k31, sizeof(__pyx_k31)},
  {&__pyx_n_MF_GRAYED, 1, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_n_MF_HELP, 1, __pyx_k28, sizeof(__pyx_k28)},
  {&__pyx_n_MF_HILITE, 1, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_n_MF_INSERT, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n_MF_MENUBARBREAK, 1, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_n_MF_MENUBREAK, 1, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_n_MF_MOUSESELECT, 1, __pyx_k30, sizeof(__pyx_k30)},
  {&__pyx_n_MF_OWNERDRAW, 1, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_n_MF_POPUP, 1, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_n_MF_REMOVE, 1, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_n_MF_RIGHTJUSTIFY, 1, __pyx_k29, sizeof(__pyx_k29)},
  {&__pyx_n_MF_SEPARATOR, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n_MF_STRING, 1, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_n_MF_SYSMENU, 1, __pyx_k27, sizeof(__pyx_k27)},
  {&__pyx_n_MF_UNCHECKED, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_n_MF_UNHILITE, 1, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_n_MF_USECHECKBITMAPS, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n___MENUCONSTS, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n__const_menu, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_getHwnd, 1, __pyx_k1, sizeof(__pyx_k1)},
  {0, 0, 0, 0}
};

static PyObject *__pyx_d1;
static long __pyx_d2;
static long __pyx_d3;


/* Implementation of _pymfclib_menu */

static PyObject *__pyx_f_14_pymfclib_menu__menu_ismenu(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_pymfclib_menu__menu_ismenu(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_r;
  HANDLE __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"hMenu",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_hMenu)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  __pyx_1 = PyMFCHandle_AsHandle(__pyx_v_hMenu); if (__pyx_1 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  __pyx_2 = c_menu_ismenu(__pyx_1); if (__pyx_2 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pymfclib_menu._menu_ismenu");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  return __pyx_r;
}

static PyObject *__pyx_f_14_pymfclib_menu__menu_create(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_pymfclib_menu__menu_create(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  HMENU __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  __pyx_1 = c_menu_create(); if (__pyx_1 == NULL) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
  __pyx_2 = PyMFCHandle_FromHandle(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("_pymfclib_menu._menu_create");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_14_pymfclib_menu__menu_createPopup(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_pymfclib_menu__menu_createPopup(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  HMENU __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  __pyx_1 = c_menu_createPopup(); if (__pyx_1 == NULL) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  __pyx_2 = PyMFCHandle_FromHandle(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("_pymfclib_menu._menu_createPopup");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_14_pymfclib_menu__menu_destroy(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_pymfclib_menu__menu_destroy(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_r;
  HANDLE __pyx_1;
  int __pyx_2;
  static char *__pyx_argnames[] = {"hMenu",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_hMenu)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  __pyx_1 = PyMFCHandle_AsHandle(__pyx_v_hMenu); if (__pyx_1 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
  __pyx_2 = c_menu_destroy(__pyx_1); if (__pyx_2 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfclib_menu._menu_destroy");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  return __pyx_r;
}

static PyObject *__pyx_f_14_pymfclib_menu__menu_insert(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_pymfclib_menu__menu_insert(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_v_nPosition = 0;
  PyObject *__pyx_v_nFlags = 0;
  PyObject *__pyx_v_nIDNewItem = 0;
  PyObject *__pyx_v_lpszNewItem = 0;
  void *__pyx_v_newitem;
  long __pyx_v_n;
  PyObject *__pyx_r;
  int __pyx_1;
  HANDLE __pyx_2;
  long __pyx_3;
  int __pyx_4;
  __pyx_t_14_pymfclib_menu_PYMFC_WCHAR *__pyx_5;
  int __pyx_6;
  static char *__pyx_argnames[] = {"hMenu","nPosition","nFlags","nIDNewItem","lpszNewItem",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOOO", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_nPosition, &__pyx_v_nFlags, &__pyx_v_nIDNewItem, &__pyx_v_lpszNewItem)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  Py_INCREF(__pyx_v_nPosition);
  Py_INCREF(__pyx_v_nFlags);
  Py_INCREF(__pyx_v_nIDNewItem);
  Py_INCREF(__pyx_v_lpszNewItem);

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":149 */
  __pyx_1 = PyMFCHandle_IsHandle(__pyx_v_nIDNewItem); if (__pyx_1 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
  if (__pyx_1) {
    __pyx_2 = PyMFCHandle_AsHandle(__pyx_v_nIDNewItem); if (__pyx_2 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    __pyx_v_newitem = __pyx_2;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":152 */
    __pyx_3 = PyInt_AsLong(__pyx_v_nIDNewItem); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    __pyx_v_n = __pyx_3;

    /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":153 */
    __pyx_v_newitem = ((void *)__pyx_v_n);
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":155 */
  __pyx_2 = PyMFCHandle_AsHandle(__pyx_v_hMenu); if (__pyx_2 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  __pyx_1 = PyInt_AsLong(__pyx_v_nPosition); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  __pyx_4 = PyInt_AsLong(__pyx_v_nFlags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  __pyx_5 = PyUnicode_AsUnicode(__pyx_v_lpszNewItem); if (__pyx_5 == NULL) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  __pyx_6 = c_menu_insert(__pyx_2,__pyx_1,__pyx_4,__pyx_v_newitem,__pyx_5); if (__pyx_6 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfclib_menu._menu_insert");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  Py_DECREF(__pyx_v_nPosition);
  Py_DECREF(__pyx_v_nFlags);
  Py_DECREF(__pyx_v_nIDNewItem);
  Py_DECREF(__pyx_v_lpszNewItem);
  return __pyx_r;
}

static PyObject *__pyx_f_14_pymfclib_menu__menu_append(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_pymfclib_menu__menu_append(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_v_nFlags = 0;
  PyObject *__pyx_v_nIDNewItem = 0;
  PyObject *__pyx_v_lpszNewItem = 0;
  void *__pyx_v_newitem;
  long __pyx_v_n;
  PyObject *__pyx_r;
  int __pyx_1;
  HANDLE __pyx_2;
  long __pyx_3;
  __pyx_t_14_pymfclib_menu_PYMFC_WCHAR *__pyx_4;
  int __pyx_5;
  static char *__pyx_argnames[] = {"hMenu","nFlags","nIDNewItem","lpszNewItem",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOO", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_nFlags, &__pyx_v_nIDNewItem, &__pyx_v_lpszNewItem)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  Py_INCREF(__pyx_v_nFlags);
  Py_INCREF(__pyx_v_nIDNewItem);
  Py_INCREF(__pyx_v_lpszNewItem);

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":160 */
  __pyx_1 = PyMFCHandle_IsHandle(__pyx_v_nIDNewItem); if (__pyx_1 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
  if (__pyx_1) {
    __pyx_2 = PyMFCHandle_AsHandle(__pyx_v_nIDNewItem); if (__pyx_2 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    __pyx_v_newitem = __pyx_2;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":163 */
    __pyx_3 = PyInt_AsLong(__pyx_v_nIDNewItem); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
    __pyx_v_n = __pyx_3;

    /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":164 */
    __pyx_v_newitem = ((void *)__pyx_v_n);
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":166 */
  __pyx_2 = PyMFCHandle_AsHandle(__pyx_v_hMenu); if (__pyx_2 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  __pyx_1 = PyInt_AsLong(__pyx_v_nFlags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  __pyx_4 = PyUnicode_AsUnicode(__pyx_v_lpszNewItem); if (__pyx_4 == NULL) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  __pyx_5 = c_menu_append(__pyx_2,__pyx_1,__pyx_v_newitem,__pyx_4); if (__pyx_5 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfclib_menu._menu_append");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  Py_DECREF(__pyx_v_nFlags);
  Py_DECREF(__pyx_v_nIDNewItem);
  Py_DECREF(__pyx_v_lpszNewItem);
  return __pyx_r;
}

static PyObject *__pyx_f_14_pymfclib_menu__menu_delete(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_pymfclib_menu__menu_delete(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_v_nPosition = 0;
  PyObject *__pyx_v_nFlags = 0;
  PyObject *__pyx_r;
  HANDLE __pyx_1;
  int __pyx_2;
  int __pyx_3;
  int __pyx_4;
  static char *__pyx_argnames[] = {"hMenu","nPosition","nFlags",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_nPosition, &__pyx_v_nFlags)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  Py_INCREF(__pyx_v_nPosition);
  Py_INCREF(__pyx_v_nFlags);
  __pyx_1 = PyMFCHandle_AsHandle(__pyx_v_hMenu); if (__pyx_1 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_nPosition); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_nFlags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
  __pyx_4 = c_menu_delete(__pyx_1,__pyx_2,__pyx_3); if (__pyx_4 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfclib_menu._menu_delete");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  Py_DECREF(__pyx_v_nPosition);
  Py_DECREF(__pyx_v_nFlags);
  return __pyx_r;
}

static PyObject *__pyx_f_14_pymfclib_menu__menu_remove(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_pymfclib_menu__menu_remove(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_v_nPosition = 0;
  PyObject *__pyx_v_nFlags = 0;
  PyObject *__pyx_r;
  HANDLE __pyx_1;
  int __pyx_2;
  int __pyx_3;
  int __pyx_4;
  static char *__pyx_argnames[] = {"hMenu","nPosition","nFlags",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_nPosition, &__pyx_v_nFlags)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  Py_INCREF(__pyx_v_nPosition);
  Py_INCREF(__pyx_v_nFlags);
  __pyx_1 = PyMFCHandle_AsHandle(__pyx_v_hMenu); if (__pyx_1 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_nPosition); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_nFlags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
  __pyx_4 = c_menu_remove(__pyx_1,__pyx_2,__pyx_3); if (__pyx_4 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfclib_menu._menu_remove");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  Py_DECREF(__pyx_v_nPosition);
  Py_DECREF(__pyx_v_nFlags);
  return __pyx_r;
}

static PyObject *__pyx_f_14_pymfclib_menu__menu_itemCount(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_pymfclib_menu__menu_itemCount(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_r;
  HANDLE __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"hMenu",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_hMenu)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  __pyx_1 = PyMFCHandle_AsHandle(__pyx_v_hMenu); if (__pyx_1 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; goto __pyx_L1;}
  __pyx_2 = c_menu_itemCount(__pyx_1); if (__pyx_2 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pymfclib_menu._menu_itemCount");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  return __pyx_r;
}

static PyObject *__pyx_f_14_pymfclib_menu__menu_getString(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_pymfclib_menu__menu_getString(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_v_nPosition = 0;
  PyObject *__pyx_v_nFlags = 0;
  PyObject *__pyx_r;
  HANDLE __pyx_1;
  int __pyx_2;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"hMenu","nPosition","nFlags",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_nPosition, &__pyx_v_nFlags)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  Py_INCREF(__pyx_v_nPosition);
  Py_INCREF(__pyx_v_nFlags);
  __pyx_1 = PyMFCHandle_AsHandle(__pyx_v_hMenu); if (__pyx_1 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_nPosition); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_nFlags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  __pyx_4 = c_menu_getString(__pyx_1,__pyx_2,__pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_pymfclib_menu._menu_getString");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  Py_DECREF(__pyx_v_nPosition);
  Py_DECREF(__pyx_v_nFlags);
  return __pyx_r;
}

static PyObject *__pyx_f_14_pymfclib_menu__menu_enable_menu_item(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_pymfclib_menu__menu_enable_menu_item(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_v_uIDEnableItem = 0;
  PyObject *__pyx_v_uEnable = 0;
  HMENU __pyx_v_hmenu;
  PyObject *__pyx_r;
  HANDLE __pyx_1;
  int __pyx_2;
  int __pyx_3;
  static char *__pyx_argnames[] = {"hMenu","uIDEnableItem","uEnable",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_uIDEnableItem, &__pyx_v_uEnable)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  Py_INCREF(__pyx_v_uIDEnableItem);
  Py_INCREF(__pyx_v_uEnable);

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":182 */
  __pyx_1 = PyMFCHandle_AsHandle(__pyx_v_hMenu); if (__pyx_1 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  __pyx_v_hmenu = __pyx_1;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":183 */
  __pyx_2 = PyInt_AsLong(__pyx_v_uIDEnableItem); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_uEnable); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
  EnableMenuItem(__pyx_v_hmenu,__pyx_2,__pyx_3);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfclib_menu._menu_enable_menu_item");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  Py_DECREF(__pyx_v_uIDEnableItem);
  Py_DECREF(__pyx_v_uEnable);
  return __pyx_r;
}

static PyObject *__pyx_f_14_pymfclib_menu__menu_track_popup_menu(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_pymfclib_menu__menu_track_popup_menu(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  long __pyx_v_x;
  long __pyx_v_y;
  PyObject *__pyx_v_wnd = 0;
  PyObject *__pyx_v_exclude = 0;
  long __pyx_v_nonotify;
  long __pyx_v_returncmd;
  int __pyx_v_f;
  HWND __pyx_v_w;
  TPMPARAMS __pyx_v_tpm;
  TPMPARAMS *__pyx_v_ptpm;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  HANDLE __pyx_4;
  long __pyx_5;
  static char *__pyx_argnames[] = {"hMenu","x","y","wnd","exclude","nonotify","returncmd",0};
  __pyx_v_exclude = __pyx_d1;
  __pyx_v_nonotify = __pyx_d2;
  __pyx_v_returncmd = __pyx_d3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OllO|Oll", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_x, &__pyx_v_y, &__pyx_v_wnd, &__pyx_v_exclude, &__pyx_v_nonotify, &__pyx_v_returncmd)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  Py_INCREF(__pyx_v_wnd);
  Py_INCREF(__pyx_v_exclude);

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":192 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_wnd,__pyx_n_getHwnd); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 192; goto __pyx_L1;}
  __pyx_2 = PyObject_IsTrue(__pyx_1); if (__pyx_2 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 192; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_2) {
    __pyx_1 = PyObject_GetAttr(__pyx_v_wnd, __pyx_n_getHwnd); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
    __pyx_3 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_4 = PyMFCHandle_AsHandle(__pyx_3); if (__pyx_4 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_v_w = __pyx_4;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_4 = PyMFCHandle_AsHandle(__pyx_v_wnd); if (__pyx_4 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
    __pyx_v_w = __pyx_4;
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":196 */
  __pyx_v_f = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":197 */
  __pyx_5 = __pyx_v_nonotify;
  if (__pyx_5) {
    __pyx_v_f = (__pyx_v_f | TPM_NONOTIFY);
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":199 */
  __pyx_5 = __pyx_v_returncmd;
  if (__pyx_5) {
    __pyx_v_f = (__pyx_v_f | TPM_RETURNCMD);
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":202 */
  __pyx_v_ptpm = NULL;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":203 */
  __pyx_2 = PyObject_IsTrue(__pyx_v_exclude); if (__pyx_2 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; goto __pyx_L1;}
  if (__pyx_2) {

    /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":204 */
    __pyx_v_ptpm = (&__pyx_v_tpm);

    /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":205 */
    __pyx_v_tpm.cbSize = (sizeof(__pyx_v_tpm));

    /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":206 */
    __pyx_1 = __Pyx_GetItemInt(__pyx_v_exclude, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
    __pyx_5 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_v_tpm.rcExclude.left = __pyx_5;

    /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":207 */
    __pyx_3 = __Pyx_GetItemInt(__pyx_v_exclude, 1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
    __pyx_5 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_v_tpm.rcExclude.top = __pyx_5;

    /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":208 */
    __pyx_1 = __Pyx_GetItemInt(__pyx_v_exclude, 2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
    __pyx_5 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_v_tpm.rcExclude.right = __pyx_5;

    /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":209 */
    __pyx_3 = __Pyx_GetItemInt(__pyx_v_exclude, 3); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
    __pyx_5 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_v_tpm.rcExclude.bottom = __pyx_5;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":211 */
  __pyx_4 = PyMFCHandle_AsHandle(__pyx_v_hMenu); if (__pyx_4 == NULL && PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  __pyx_2 = c_menu_track_popup_menu(__pyx_4,__pyx_v_f,__pyx_v_x,__pyx_v_y,__pyx_v_w,__pyx_v_ptpm); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  __pyx_1 = PyInt_FromLong(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pymfclib_menu._menu_track_popup_menu");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  Py_DECREF(__pyx_v_wnd);
  Py_DECREF(__pyx_v_exclude);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"_menu_ismenu", (PyCFunction)__pyx_f_14_pymfclib_menu__menu_ismenu, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_create", (PyCFunction)__pyx_f_14_pymfclib_menu__menu_create, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_createPopup", (PyCFunction)__pyx_f_14_pymfclib_menu__menu_createPopup, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_destroy", (PyCFunction)__pyx_f_14_pymfclib_menu__menu_destroy, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_insert", (PyCFunction)__pyx_f_14_pymfclib_menu__menu_insert, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_append", (PyCFunction)__pyx_f_14_pymfclib_menu__menu_append, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_delete", (PyCFunction)__pyx_f_14_pymfclib_menu__menu_delete, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_remove", (PyCFunction)__pyx_f_14_pymfclib_menu__menu_remove, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_itemCount", (PyCFunction)__pyx_f_14_pymfclib_menu__menu_itemCount, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_getString", (PyCFunction)__pyx_f_14_pymfclib_menu__menu_getString, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_enable_menu_item", (PyCFunction)__pyx_f_14_pymfclib_menu__menu_enable_menu_item, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_track_popup_menu", (PyCFunction)__pyx_f_14_pymfclib_menu__menu_track_popup_menu, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC init_pymfclib_menu(void); /*proto*/
PyMODINIT_FUNC init_pymfclib_menu(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("_pymfclib_menu", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  __pyx_v_14_pymfclib_menu___const_menu = Py_None; Py_INCREF(Py_None);

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":80 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n___MENUCONSTS, "_pymfclib_menu"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n___MENUCONSTS, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":83 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n___MENUCONSTS); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n__const_menu, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":85 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n__const_menu); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  Py_DECREF(__pyx_v_14_pymfclib_menu___const_menu);
  __pyx_v_14_pymfclib_menu___const_menu = __pyx_1;
  __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":87 */
  __pyx_2 = PyInt_FromLong(MF_INSERT); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_INSERT, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":88 */
  __pyx_3 = PyInt_FromLong(MF_CHANGE); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_CHANGE, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":89 */
  __pyx_1 = PyInt_FromLong(MF_APPEND); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_APPEND, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":90 */
  __pyx_2 = PyInt_FromLong(MF_DELETE); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_DELETE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":91 */
  __pyx_3 = PyInt_FromLong(MF_REMOVE); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_REMOVE, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":92 */
  __pyx_1 = PyInt_FromLong(MF_BYCOMMAND); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_BYCOMMAND, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":93 */
  __pyx_2 = PyInt_FromLong(MF_BYPOSITION); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_BYPOSITION, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":94 */
  __pyx_3 = PyInt_FromLong(MF_SEPARATOR); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_SEPARATOR, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":95 */
  __pyx_1 = PyInt_FromLong(MF_ENABLED); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_ENABLED, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":96 */
  __pyx_2 = PyInt_FromLong(MF_GRAYED); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_GRAYED, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":97 */
  __pyx_3 = PyInt_FromLong(MF_DISABLED); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_DISABLED, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":98 */
  __pyx_1 = PyInt_FromLong(MF_UNCHECKED); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_UNCHECKED, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":99 */
  __pyx_2 = PyInt_FromLong(MF_CHECKED); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_CHECKED, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":100 */
  __pyx_3 = PyInt_FromLong(MF_USECHECKBITMAPS); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_USECHECKBITMAPS, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":101 */
  __pyx_1 = PyInt_FromLong(MF_STRING); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_STRING, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":102 */
  __pyx_2 = PyInt_FromLong(MF_BITMAP); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_BITMAP, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":103 */
  __pyx_3 = PyInt_FromLong(MF_OWNERDRAW); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_OWNERDRAW, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":104 */
  __pyx_1 = PyInt_FromLong(MF_POPUP); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_POPUP, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":105 */
  __pyx_2 = PyInt_FromLong(MF_MENUBARBREAK); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_MENUBARBREAK, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":106 */
  __pyx_3 = PyInt_FromLong(MF_MENUBREAK); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_MENUBREAK, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":107 */
  __pyx_1 = PyInt_FromLong(MF_UNHILITE); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_UNHILITE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":108 */
  __pyx_2 = PyInt_FromLong(MF_HILITE); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_HILITE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":109 */
  __pyx_3 = PyInt_FromLong(MF_DEFAULT); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_DEFAULT, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":110 */
  __pyx_1 = PyInt_FromLong(MF_SYSMENU); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_SYSMENU, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":111 */
  __pyx_2 = PyInt_FromLong(MF_HELP); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_HELP, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":112 */
  __pyx_3 = PyInt_FromLong(MF_RIGHTJUSTIFY); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_RIGHTJUSTIFY, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":113 */
  __pyx_1 = PyInt_FromLong(MF_MOUSESELECT); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_MOUSESELECT, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":114 */
  __pyx_2 = PyInt_FromLong(MF_END); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MF_END, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":115 */
  __pyx_3 = PyInt_FromLong(MFT_STRING); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFT_STRING, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":116 */
  __pyx_1 = PyInt_FromLong(MFT_BITMAP); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFT_BITMAP, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":117 */
  __pyx_2 = PyInt_FromLong(MFT_MENUBARBREAK); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFT_MENUBARBREAK, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":118 */
  __pyx_3 = PyInt_FromLong(MFT_MENUBREAK); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFT_MENUBREAK, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":119 */
  __pyx_1 = PyInt_FromLong(MFT_OWNERDRAW); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFT_OWNERDRAW, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":120 */
  __pyx_2 = PyInt_FromLong(MFT_RADIOCHECK); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFT_RADIOCHECK, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":121 */
  __pyx_3 = PyInt_FromLong(MFT_SEPARATOR); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFT_SEPARATOR, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":122 */
  __pyx_1 = PyInt_FromLong(MFT_RIGHTORDER); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFT_RIGHTORDER, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":123 */
  __pyx_2 = PyInt_FromLong(MFT_RIGHTJUSTIFY); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFT_RIGHTJUSTIFY, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":124 */
  __pyx_3 = PyInt_FromLong(MFS_GRAYED); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFS_GRAYED, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":125 */
  __pyx_1 = PyInt_FromLong(MFS_DISABLED); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFS_DISABLED, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":126 */
  __pyx_2 = PyInt_FromLong(MFS_CHECKED); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFS_CHECKED, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":127 */
  __pyx_3 = PyInt_FromLong(MFS_HILITE); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFS_HILITE, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":128 */
  __pyx_1 = PyInt_FromLong(MFS_ENABLED); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFS_ENABLED, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":129 */
  __pyx_2 = PyInt_FromLong(MFS_UNCHECKED); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFS_UNCHECKED, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":130 */
  __pyx_3 = PyInt_FromLong(MFS_UNHILITE); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFS_UNHILITE, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":131 */
  __pyx_1 = PyInt_FromLong(MFS_DEFAULT); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_14_pymfclib_menu___const_menu, __pyx_n_MFS_DEFAULT, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfc\pymfclib\_pymfclib_menu.pyx":186 */
  Py_INCREF(Py_None);
  __pyx_d1 = Py_None;
  __pyx_d2 = 0;
  __pyx_d3 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pymfclib_menu");
}

static char *__pyx_filenames[] = {
  "_pymfclib_menu.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetItemInt(PyObject *o, Py_ssize_t i) {
    PyTypeObject *t = o->ob_type;
    PyObject *r;
    if (t->tp_as_sequence && t->tp_as_sequence->sq_item)
        r = PySequence_GetItem(o, i);
    else {
        PyObject *j = PyInt_FromLong(i);
        if (!j)
            return 0;
        r = PyObject_GetItem(o, j);
        Py_DECREF(j);
    }
    return r;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
