/* Generated by Pyrex 0.9.3 on Wed Apr 06 16:32:00 2005 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "mfcpragma.h"
#include "pymfcdefs.h"
#include "windows.h"
#include "COMMCTRL.H"
#include "pymwin32funcs.h"
#include "pymwnd.h"
#include "pymmenu.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

/* Declarations from _pymfc_menu */

static PyObject *__pyx_v_11_pymfc_menu___const_menu;
static PyObject *__pyx_k2;
static long __pyx_k3;
static long __pyx_k4;

/* Implementation of _pymfc_menu */


static PyObject *__pyx_n___MENUCONSTS;
static PyObject *__pyx_n__const_menu;
static PyObject *__pyx_n__menu_ismenu;
static PyObject *__pyx_n__menu_create;
static PyObject *__pyx_n__menu_createPopup;
static PyObject *__pyx_n__menu_destroy;
static PyObject *__pyx_n__menu_insert;
static PyObject *__pyx_n__menu_append;
static PyObject *__pyx_n__menu_delete;
static PyObject *__pyx_n__menu_remove;
static PyObject *__pyx_n__menu_itemCount;
static PyObject *__pyx_n__menu_getString;
static PyObject *__pyx_n__menu_enable_menu_item;
static PyObject *__pyx_n__menu_track_popup_menu;
static PyObject *__pyx_n_MF_INSERT;
static PyObject *__pyx_n_MF_CHANGE;
static PyObject *__pyx_n_MF_APPEND;
static PyObject *__pyx_n_MF_DELETE;
static PyObject *__pyx_n_MF_REMOVE;
static PyObject *__pyx_n_MF_BYCOMMAND;
static PyObject *__pyx_n_MF_BYPOSITION;
static PyObject *__pyx_n_MF_SEPARATOR;
static PyObject *__pyx_n_MF_ENABLED;
static PyObject *__pyx_n_MF_GRAYED;
static PyObject *__pyx_n_MF_DISABLED;
static PyObject *__pyx_n_MF_UNCHECKED;
static PyObject *__pyx_n_MF_CHECKED;
static PyObject *__pyx_n_MF_USECHECKBITMAPS;
static PyObject *__pyx_n_MF_STRING;
static PyObject *__pyx_n_MF_BITMAP;
static PyObject *__pyx_n_MF_OWNERDRAW;
static PyObject *__pyx_n_MF_POPUP;
static PyObject *__pyx_n_MF_MENUBARBREAK;
static PyObject *__pyx_n_MF_MENUBREAK;
static PyObject *__pyx_n_MF_UNHILITE;
static PyObject *__pyx_n_MF_HILITE;
static PyObject *__pyx_n_MF_DEFAULT;
static PyObject *__pyx_n_MF_SYSMENU;
static PyObject *__pyx_n_MF_HELP;
static PyObject *__pyx_n_MF_RIGHTJUSTIFY;
static PyObject *__pyx_n_MF_MOUSESELECT;
static PyObject *__pyx_n_MF_END;
static PyObject *__pyx_n_MFT_STRING;
static PyObject *__pyx_n_MFT_BITMAP;
static PyObject *__pyx_n_MFT_MENUBARBREAK;
static PyObject *__pyx_n_MFT_MENUBREAK;
static PyObject *__pyx_n_MFT_OWNERDRAW;
static PyObject *__pyx_n_MFT_RADIOCHECK;
static PyObject *__pyx_n_MFT_SEPARATOR;
static PyObject *__pyx_n_MFT_RIGHTORDER;
static PyObject *__pyx_n_MFT_RIGHTJUSTIFY;
static PyObject *__pyx_n_MFS_GRAYED;
static PyObject *__pyx_n_MFS_DISABLED;
static PyObject *__pyx_n_MFS_CHECKED;
static PyObject *__pyx_n_MFS_HILITE;
static PyObject *__pyx_n_MFS_ENABLED;
static PyObject *__pyx_n_MFS_UNCHECKED;
static PyObject *__pyx_n_MFS_UNHILITE;
static PyObject *__pyx_n_MFS_DEFAULT;

static PyObject *__pyx_f_11_pymfc_menu__menu_ismenu(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_pymfc_menu__menu_ismenu(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"hMenu",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_hMenu)) return 0;
  Py_INCREF(__pyx_v_hMenu);

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":135 */
  __pyx_1 = PyInt_AsLong(__pyx_v_hMenu); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  __pyx_2 = c_menu_ismenu(__pyx_1); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pymfc_menu._menu_ismenu");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  return __pyx_r;
}

static PyObject *__pyx_f_11_pymfc_menu__menu_create(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_pymfc_menu__menu_create(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  long __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":138 */
  __pyx_1 = c_menu_create(); if (__pyx_1 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("_pymfc_menu._menu_create");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_11_pymfc_menu__menu_createPopup(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_pymfc_menu__menu_createPopup(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  long __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":141 */
  __pyx_1 = c_menu_createPopup(); if (__pyx_1 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("_pymfc_menu._menu_createPopup");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_11_pymfc_menu__menu_destroy(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_pymfc_menu__menu_destroy(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  static char *__pyx_argnames[] = {"hMenu",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_hMenu)) return 0;
  Py_INCREF(__pyx_v_hMenu);

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":144 */
  __pyx_1 = PyInt_AsLong(__pyx_v_hMenu); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
  __pyx_2 = c_menu_destroy(__pyx_1); if (__pyx_2 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfc_menu._menu_destroy");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  return __pyx_r;
}

static PyObject *__pyx_f_11_pymfc_menu__menu_insert(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_pymfc_menu__menu_insert(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_v_nPosition = 0;
  PyObject *__pyx_v_nFlags = 0;
  PyObject *__pyx_v_nIDNewItem = 0;
  PyObject *__pyx_v_lpszNewItem = 0;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  int __pyx_3;
  int __pyx_4;
  char (*__pyx_5);
  int __pyx_6;
  static char *__pyx_argnames[] = {"hMenu","nPosition","nFlags","nIDNewItem","lpszNewItem",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOOO", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_nPosition, &__pyx_v_nFlags, &__pyx_v_nIDNewItem, &__pyx_v_lpszNewItem)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  Py_INCREF(__pyx_v_nPosition);
  Py_INCREF(__pyx_v_nFlags);
  Py_INCREF(__pyx_v_nIDNewItem);
  Py_INCREF(__pyx_v_lpszNewItem);

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":147 */
  __pyx_1 = PyInt_AsLong(__pyx_v_hMenu); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_nPosition); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_nFlags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  __pyx_4 = PyInt_AsLong(__pyx_v_nIDNewItem); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  __pyx_5 = PyString_AsString(__pyx_v_lpszNewItem); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  __pyx_6 = c_menu_insert(__pyx_1,__pyx_2,__pyx_3,__pyx_4,__pyx_5); if (__pyx_6 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfc_menu._menu_insert");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  Py_DECREF(__pyx_v_nPosition);
  Py_DECREF(__pyx_v_nFlags);
  Py_DECREF(__pyx_v_nIDNewItem);
  Py_DECREF(__pyx_v_lpszNewItem);
  return __pyx_r;
}

static PyObject *__pyx_f_11_pymfc_menu__menu_append(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_pymfc_menu__menu_append(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_v_nFlags = 0;
  PyObject *__pyx_v_nIDNewItem = 0;
  PyObject *__pyx_v_lpszNewItem = 0;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  int __pyx_3;
  char (*__pyx_4);
  int __pyx_5;
  static char *__pyx_argnames[] = {"hMenu","nFlags","nIDNewItem","lpszNewItem",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOO", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_nFlags, &__pyx_v_nIDNewItem, &__pyx_v_lpszNewItem)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  Py_INCREF(__pyx_v_nFlags);
  Py_INCREF(__pyx_v_nIDNewItem);
  Py_INCREF(__pyx_v_lpszNewItem);

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":150 */
  __pyx_1 = PyInt_AsLong(__pyx_v_hMenu); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_nFlags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_nIDNewItem); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_4 = PyString_AsString(__pyx_v_lpszNewItem); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_5 = c_menu_append(__pyx_1,__pyx_2,__pyx_3,__pyx_4); if (__pyx_5 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfc_menu._menu_append");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  Py_DECREF(__pyx_v_nFlags);
  Py_DECREF(__pyx_v_nIDNewItem);
  Py_DECREF(__pyx_v_lpszNewItem);
  return __pyx_r;
}

static PyObject *__pyx_f_11_pymfc_menu__menu_delete(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_pymfc_menu__menu_delete(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_v_nPosition = 0;
  PyObject *__pyx_v_nFlags = 0;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  int __pyx_3;
  int __pyx_4;
  static char *__pyx_argnames[] = {"hMenu","nPosition","nFlags",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_nPosition, &__pyx_v_nFlags)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  Py_INCREF(__pyx_v_nPosition);
  Py_INCREF(__pyx_v_nFlags);

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":153 */
  __pyx_1 = PyInt_AsLong(__pyx_v_hMenu); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_nPosition); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_nFlags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
  __pyx_4 = c_menu_delete(__pyx_1,__pyx_2,__pyx_3); if (__pyx_4 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfc_menu._menu_delete");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  Py_DECREF(__pyx_v_nPosition);
  Py_DECREF(__pyx_v_nFlags);
  return __pyx_r;
}

static PyObject *__pyx_f_11_pymfc_menu__menu_remove(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_pymfc_menu__menu_remove(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_v_nPosition = 0;
  PyObject *__pyx_v_nFlags = 0;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  int __pyx_3;
  int __pyx_4;
  static char *__pyx_argnames[] = {"hMenu","nPosition","nFlags",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_nPosition, &__pyx_v_nFlags)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  Py_INCREF(__pyx_v_nPosition);
  Py_INCREF(__pyx_v_nFlags);

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":156 */
  __pyx_1 = PyInt_AsLong(__pyx_v_hMenu); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_nPosition); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_nFlags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
  __pyx_4 = c_menu_remove(__pyx_1,__pyx_2,__pyx_3); if (__pyx_4 == 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfc_menu._menu_remove");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  Py_DECREF(__pyx_v_nPosition);
  Py_DECREF(__pyx_v_nFlags);
  return __pyx_r;
}

static PyObject *__pyx_f_11_pymfc_menu__menu_itemCount(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_pymfc_menu__menu_itemCount(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"hMenu",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_hMenu)) return 0;
  Py_INCREF(__pyx_v_hMenu);

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":159 */
  __pyx_1 = PyInt_AsLong(__pyx_v_hMenu); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 159; goto __pyx_L1;}
  __pyx_2 = c_menu_itemCount(__pyx_1); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 159; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 159; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pymfc_menu._menu_itemCount");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  return __pyx_r;
}

static PyObject *__pyx_f_11_pymfc_menu__menu_getString(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_pymfc_menu__menu_getString(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenu = 0;
  PyObject *__pyx_v_nPosition = 0;
  PyObject *__pyx_v_nFlags = 0;
  PyObject *__pyx_r;
  long __pyx_1;
  int __pyx_2;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"hMenu","nPosition","nFlags",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_nPosition, &__pyx_v_nFlags)) return 0;
  Py_INCREF(__pyx_v_hMenu);
  Py_INCREF(__pyx_v_nPosition);
  Py_INCREF(__pyx_v_nFlags);

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":162 */
  __pyx_1 = PyInt_AsLong(__pyx_v_hMenu); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_nPosition); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_nFlags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
  __pyx_4 = c_menu_getString(__pyx_1,__pyx_2,__pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_pymfc_menu._menu_getString");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenu);
  Py_DECREF(__pyx_v_nPosition);
  Py_DECREF(__pyx_v_nFlags);
  return __pyx_r;
}

static PyObject *__pyx_f_11_pymfc_menu__menu_enable_menu_item(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_pymfc_menu__menu_enable_menu_item(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_hMenu;
  PyObject *__pyx_v_uIDEnableItem = 0;
  PyObject *__pyx_v_uEnable = 0;
  HMENU __pyx_v_hmenu;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  static char *__pyx_argnames[] = {"hMenu","uIDEnableItem","uEnable",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "lOO", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_uIDEnableItem, &__pyx_v_uEnable)) return 0;
  Py_INCREF(__pyx_v_uIDEnableItem);
  Py_INCREF(__pyx_v_uEnable);

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":166 */
  __pyx_v_hmenu = ((HMENU )__pyx_v_hMenu);

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":167 */
  __pyx_1 = PyInt_AsLong(__pyx_v_uIDEnableItem); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_uEnable); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  EnableMenuItem(__pyx_v_hmenu,__pyx_1,__pyx_2);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pymfc_menu._menu_enable_menu_item");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_uIDEnableItem);
  Py_DECREF(__pyx_v_uEnable);
  return __pyx_r;
}

static PyObject *__pyx_n_getattr;
static PyObject *__pyx_n_getHwnd;
static PyObject *__pyx_n_hwnd;


static PyObject *__pyx_f_11_pymfc_menu__menu_track_popup_menu(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_pymfc_menu__menu_track_popup_menu(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_hMenu;
  long __pyx_v_x;
  long __pyx_v_y;
  PyObject *__pyx_v_wnd = 0;
  PyObject *__pyx_v_exclude = 0;
  long __pyx_v_nonotify;
  long __pyx_v_returncmd;
  int __pyx_v_f;
  long __pyx_v_w;
  TPMPARAMS __pyx_v_tpm;
  TPMPARAMS (*__pyx_v_ptpm);
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  long __pyx_5;
  static char *__pyx_argnames[] = {"hMenu","x","y","wnd","exclude","nonotify","returncmd",0};
  __pyx_v_exclude = __pyx_k2;
  __pyx_v_nonotify = __pyx_k3;
  __pyx_v_returncmd = __pyx_k4;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "lllO|Oll", __pyx_argnames, &__pyx_v_hMenu, &__pyx_v_x, &__pyx_v_y, &__pyx_v_wnd, &__pyx_v_exclude, &__pyx_v_nonotify, &__pyx_v_returncmd)) return 0;
  Py_INCREF(__pyx_v_wnd);
  Py_INCREF(__pyx_v_exclude);

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":176 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_getattr); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  Py_INCREF(__pyx_v_wnd);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_wnd);
  Py_INCREF(__pyx_n_getHwnd);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_n_getHwnd);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {

    /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":177 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_wnd, __pyx_n_getHwnd); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
    __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_5 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_v_w = __pyx_5;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":179 */
    __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_hwnd); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
    __pyx_5 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_v_w = __pyx_5;
  }
  __pyx_L2:;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":180 */
  __pyx_v_f = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":181 */
  __pyx_5 = __pyx_v_nonotify;
  if (__pyx_5) {

    /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":182 */
    __pyx_v_f = (__pyx_v_f | TPM_NONOTIFY);
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":183 */
  __pyx_5 = __pyx_v_returncmd;
  if (__pyx_5) {

    /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":184 */
    __pyx_v_f = (__pyx_v_f | TPM_RETURNCMD);
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":186 */
  __pyx_v_ptpm = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":187 */
  __pyx_4 = PyObject_IsTrue(__pyx_v_exclude); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 187; goto __pyx_L1;}
  if (__pyx_4) {

    /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":188 */
    __pyx_v_ptpm = (&__pyx_v_tpm);

    /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":189 */
    __pyx_v_tpm.cbSize = (sizeof(__pyx_v_tpm));

    /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":190 */
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_v_exclude, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_5 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_v_tpm.rcExclude.left = __pyx_5;

    /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":191 */
    __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
    __pyx_2 = PyObject_GetItem(__pyx_v_exclude, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_5 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_tpm.rcExclude.top = __pyx_5;

    /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":192 */
    __pyx_3 = PyInt_FromLong(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 192; goto __pyx_L1;}
    __pyx_1 = PyObject_GetItem(__pyx_v_exclude, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 192; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_5 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 192; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_v_tpm.rcExclude.right = __pyx_5;

    /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":193 */
    __pyx_2 = PyInt_FromLong(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_v_exclude, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_5 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_v_tpm.rcExclude.bottom = __pyx_5;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":195 */
  __pyx_4 = c_menu_track_popup_menu(__pyx_v_hMenu,__pyx_v_f,__pyx_v_x,__pyx_v_y,((void (*))__pyx_v_w),__pyx_v_ptpm); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
  __pyx_1 = PyInt_FromLong(__pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pymfc_menu._menu_track_popup_menu");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_wnd);
  Py_DECREF(__pyx_v_exclude);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_MFS_CHECKED, "MFS_CHECKED"},
  {&__pyx_n_MFS_DEFAULT, "MFS_DEFAULT"},
  {&__pyx_n_MFS_DISABLED, "MFS_DISABLED"},
  {&__pyx_n_MFS_ENABLED, "MFS_ENABLED"},
  {&__pyx_n_MFS_GRAYED, "MFS_GRAYED"},
  {&__pyx_n_MFS_HILITE, "MFS_HILITE"},
  {&__pyx_n_MFS_UNCHECKED, "MFS_UNCHECKED"},
  {&__pyx_n_MFS_UNHILITE, "MFS_UNHILITE"},
  {&__pyx_n_MFT_BITMAP, "MFT_BITMAP"},
  {&__pyx_n_MFT_MENUBARBREAK, "MFT_MENUBARBREAK"},
  {&__pyx_n_MFT_MENUBREAK, "MFT_MENUBREAK"},
  {&__pyx_n_MFT_OWNERDRAW, "MFT_OWNERDRAW"},
  {&__pyx_n_MFT_RADIOCHECK, "MFT_RADIOCHECK"},
  {&__pyx_n_MFT_RIGHTJUSTIFY, "MFT_RIGHTJUSTIFY"},
  {&__pyx_n_MFT_RIGHTORDER, "MFT_RIGHTORDER"},
  {&__pyx_n_MFT_SEPARATOR, "MFT_SEPARATOR"},
  {&__pyx_n_MFT_STRING, "MFT_STRING"},
  {&__pyx_n_MF_APPEND, "MF_APPEND"},
  {&__pyx_n_MF_BITMAP, "MF_BITMAP"},
  {&__pyx_n_MF_BYCOMMAND, "MF_BYCOMMAND"},
  {&__pyx_n_MF_BYPOSITION, "MF_BYPOSITION"},
  {&__pyx_n_MF_CHANGE, "MF_CHANGE"},
  {&__pyx_n_MF_CHECKED, "MF_CHECKED"},
  {&__pyx_n_MF_DEFAULT, "MF_DEFAULT"},
  {&__pyx_n_MF_DELETE, "MF_DELETE"},
  {&__pyx_n_MF_DISABLED, "MF_DISABLED"},
  {&__pyx_n_MF_ENABLED, "MF_ENABLED"},
  {&__pyx_n_MF_END, "MF_END"},
  {&__pyx_n_MF_GRAYED, "MF_GRAYED"},
  {&__pyx_n_MF_HELP, "MF_HELP"},
  {&__pyx_n_MF_HILITE, "MF_HILITE"},
  {&__pyx_n_MF_INSERT, "MF_INSERT"},
  {&__pyx_n_MF_MENUBARBREAK, "MF_MENUBARBREAK"},
  {&__pyx_n_MF_MENUBREAK, "MF_MENUBREAK"},
  {&__pyx_n_MF_MOUSESELECT, "MF_MOUSESELECT"},
  {&__pyx_n_MF_OWNERDRAW, "MF_OWNERDRAW"},
  {&__pyx_n_MF_POPUP, "MF_POPUP"},
  {&__pyx_n_MF_REMOVE, "MF_REMOVE"},
  {&__pyx_n_MF_RIGHTJUSTIFY, "MF_RIGHTJUSTIFY"},
  {&__pyx_n_MF_SEPARATOR, "MF_SEPARATOR"},
  {&__pyx_n_MF_STRING, "MF_STRING"},
  {&__pyx_n_MF_SYSMENU, "MF_SYSMENU"},
  {&__pyx_n_MF_UNCHECKED, "MF_UNCHECKED"},
  {&__pyx_n_MF_UNHILITE, "MF_UNHILITE"},
  {&__pyx_n_MF_USECHECKBITMAPS, "MF_USECHECKBITMAPS"},
  {&__pyx_n___MENUCONSTS, "__MENUCONSTS"},
  {&__pyx_n__const_menu, "_const_menu"},
  {&__pyx_n__menu_append, "_menu_append"},
  {&__pyx_n__menu_create, "_menu_create"},
  {&__pyx_n__menu_createPopup, "_menu_createPopup"},
  {&__pyx_n__menu_delete, "_menu_delete"},
  {&__pyx_n__menu_destroy, "_menu_destroy"},
  {&__pyx_n__menu_enable_menu_item, "_menu_enable_menu_item"},
  {&__pyx_n__menu_getString, "_menu_getString"},
  {&__pyx_n__menu_insert, "_menu_insert"},
  {&__pyx_n__menu_ismenu, "_menu_ismenu"},
  {&__pyx_n__menu_itemCount, "_menu_itemCount"},
  {&__pyx_n__menu_remove, "_menu_remove"},
  {&__pyx_n__menu_track_popup_menu, "_menu_track_popup_menu"},
  {&__pyx_n_getHwnd, "getHwnd"},
  {&__pyx_n_getattr, "getattr"},
  {&__pyx_n_hwnd, "hwnd"},
  {0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"_menu_ismenu", (PyCFunction)__pyx_f_11_pymfc_menu__menu_ismenu, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_create", (PyCFunction)__pyx_f_11_pymfc_menu__menu_create, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_createPopup", (PyCFunction)__pyx_f_11_pymfc_menu__menu_createPopup, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_destroy", (PyCFunction)__pyx_f_11_pymfc_menu__menu_destroy, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_insert", (PyCFunction)__pyx_f_11_pymfc_menu__menu_insert, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_append", (PyCFunction)__pyx_f_11_pymfc_menu__menu_append, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_delete", (PyCFunction)__pyx_f_11_pymfc_menu__menu_delete, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_remove", (PyCFunction)__pyx_f_11_pymfc_menu__menu_remove, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_itemCount", (PyCFunction)__pyx_f_11_pymfc_menu__menu_itemCount, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_getString", (PyCFunction)__pyx_f_11_pymfc_menu__menu_getString, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_enable_menu_item", (PyCFunction)__pyx_f_11_pymfc_menu__menu_enable_menu_item, METH_VARARGS|METH_KEYWORDS, 0},
  {"_menu_track_popup_menu", (PyCFunction)__pyx_f_11_pymfc_menu__menu_track_popup_menu, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

DL_EXPORT(void) init_pymfc_menu(void); /*proto*/
DL_EXPORT(void) init_pymfc_menu(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_m = Py_InitModule4("_pymfc_menu", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  __pyx_v_11_pymfc_menu___const_menu = Py_None; Py_INCREF(__pyx_v_11_pymfc_menu___const_menu);

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":80 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n___MENUCONSTS, "_pymfc_menu"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":81 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n___MENUCONSTS, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":83 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n___MENUCONSTS); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n__const_menu, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":85 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n__const_menu); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  Py_DECREF(__pyx_v_11_pymfc_menu___const_menu);
  __pyx_v_11_pymfc_menu___const_menu = __pyx_2;
  __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":87 */
  __pyx_1 = PyInt_FromLong(MF_INSERT); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_INSERT, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":88 */
  __pyx_3 = PyInt_FromLong(MF_CHANGE); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_CHANGE, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":89 */
  __pyx_2 = PyInt_FromLong(MF_APPEND); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_APPEND, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":90 */
  __pyx_1 = PyInt_FromLong(MF_DELETE); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_DELETE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":91 */
  __pyx_3 = PyInt_FromLong(MF_REMOVE); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_REMOVE, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":92 */
  __pyx_2 = PyInt_FromLong(MF_BYCOMMAND); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_BYCOMMAND, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":93 */
  __pyx_1 = PyInt_FromLong(MF_BYPOSITION); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_BYPOSITION, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":94 */
  __pyx_3 = PyInt_FromLong(MF_SEPARATOR); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_SEPARATOR, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":95 */
  __pyx_2 = PyInt_FromLong(MF_ENABLED); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_ENABLED, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":96 */
  __pyx_1 = PyInt_FromLong(MF_GRAYED); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_GRAYED, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":97 */
  __pyx_3 = PyInt_FromLong(MF_DISABLED); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_DISABLED, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":98 */
  __pyx_2 = PyInt_FromLong(MF_UNCHECKED); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_UNCHECKED, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":99 */
  __pyx_1 = PyInt_FromLong(MF_CHECKED); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_CHECKED, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":100 */
  __pyx_3 = PyInt_FromLong(MF_USECHECKBITMAPS); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_USECHECKBITMAPS, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":101 */
  __pyx_2 = PyInt_FromLong(MF_STRING); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_STRING, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":102 */
  __pyx_1 = PyInt_FromLong(MF_BITMAP); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_BITMAP, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":103 */
  __pyx_3 = PyInt_FromLong(MF_OWNERDRAW); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_OWNERDRAW, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":104 */
  __pyx_2 = PyInt_FromLong(MF_POPUP); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_POPUP, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":105 */
  __pyx_1 = PyInt_FromLong(MF_MENUBARBREAK); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_MENUBARBREAK, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":106 */
  __pyx_3 = PyInt_FromLong(MF_MENUBREAK); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_MENUBREAK, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":107 */
  __pyx_2 = PyInt_FromLong(MF_UNHILITE); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_UNHILITE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":108 */
  __pyx_1 = PyInt_FromLong(MF_HILITE); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_HILITE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":109 */
  __pyx_3 = PyInt_FromLong(MF_DEFAULT); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_DEFAULT, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":110 */
  __pyx_2 = PyInt_FromLong(MF_SYSMENU); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_SYSMENU, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":111 */
  __pyx_1 = PyInt_FromLong(MF_HELP); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_HELP, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":112 */
  __pyx_3 = PyInt_FromLong(MF_RIGHTJUSTIFY); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_RIGHTJUSTIFY, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":113 */
  __pyx_2 = PyInt_FromLong(MF_MOUSESELECT); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_MOUSESELECT, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":114 */
  __pyx_1 = PyInt_FromLong(MF_END); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MF_END, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":115 */
  __pyx_3 = PyInt_FromLong(MFT_STRING); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFT_STRING, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":116 */
  __pyx_2 = PyInt_FromLong(MFT_BITMAP); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFT_BITMAP, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":117 */
  __pyx_1 = PyInt_FromLong(MFT_MENUBARBREAK); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFT_MENUBARBREAK, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":118 */
  __pyx_3 = PyInt_FromLong(MFT_MENUBREAK); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFT_MENUBREAK, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":119 */
  __pyx_2 = PyInt_FromLong(MFT_OWNERDRAW); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFT_OWNERDRAW, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":120 */
  __pyx_1 = PyInt_FromLong(MFT_RADIOCHECK); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFT_RADIOCHECK, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":121 */
  __pyx_3 = PyInt_FromLong(MFT_SEPARATOR); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFT_SEPARATOR, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":122 */
  __pyx_2 = PyInt_FromLong(MFT_RIGHTORDER); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFT_RIGHTORDER, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":123 */
  __pyx_1 = PyInt_FromLong(MFT_RIGHTJUSTIFY); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFT_RIGHTJUSTIFY, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":124 */
  __pyx_3 = PyInt_FromLong(MFS_GRAYED); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFS_GRAYED, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":125 */
  __pyx_2 = PyInt_FromLong(MFS_DISABLED); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFS_DISABLED, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":126 */
  __pyx_1 = PyInt_FromLong(MFS_CHECKED); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFS_CHECKED, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":127 */
  __pyx_3 = PyInt_FromLong(MFS_HILITE); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFS_HILITE, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":128 */
  __pyx_2 = PyInt_FromLong(MFS_ENABLED); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFS_ENABLED, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":129 */
  __pyx_1 = PyInt_FromLong(MFS_UNCHECKED); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFS_UNCHECKED, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":130 */
  __pyx_3 = PyInt_FromLong(MFS_UNHILITE); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFS_UNHILITE, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":131 */
  __pyx_2 = PyInt_FromLong(MFS_DEFAULT); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_11_pymfc_menu___const_menu, __pyx_n_MFS_DEFAULT, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "c:\src\infopile\src\pymfclib\_pymfc_menu.pyx":170 */
  Py_INCREF(Py_None);
  __pyx_k2 = Py_None;
  __pyx_k3 = 0;
  __pyx_k4 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pymfc_menu");
}

static char *__pyx_filenames[] = {
  "_pymfc_menu.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
